id = "codeowners"
name = "CODEOWNERS"
description = "Syntax highlighting and language support for GitHub CODEOWNERS files"
version = "0.1.0"
schema_version = 1
authors = ["Lukas Malkmus <mail@lukasmalkmus.com>"]
repository = "https://github.com/lukasmalkmus/codeowners-zed"

[grammars.codeowners]
repository = "https://github.com/lukasmalkmus/tree-sitter-codeowners"
commit = "5fc25f72a44d2fe5b9218c712062dcec79dac87e"
